add_newline = true
command_timeout = 300
continuation_prompt = '[â¯â¯â¯](#A5D6A7) '
format = "$battery[$username$hostname](blue) $directory$git_branch$character"
right_format = "$git_status $git_metrics $cmd_duration"

[character]
error_symbol = "[â¯â¯â¯](bold red)"
success_symbol = "[â¯](bold #A5D6A7)[â¯](bold #FFF59D)[â¯](bold #FFAB91)"

[directory]
repo_root_style = "underline"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_metrics]
disabled = false

[hostname]
format = " @[$ssh_symbol](bold)$hostname "
ssh_only = true

[package]
disabled = true

[ruby]
format = " [$symbol$version]($style)"
symbol = ' ğŸ’'

[python]
format = " [$symbol$version]($style)"

[username]
format = "[$user]($style)"
show_always = true
style_root = "red bold"
style_user = "blue"

[gcloud]
disabled = true

[nodejs]
disabled = true

[cmd_duration]
format = ' [$duration]($style) '
min_time_to_notify = 45000
show_notifications = true

[battery]
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
format = '[$symbol$percentage]($style) '
